### PR TITLE
fix: cache-to and from splitting single values on comma

### LINKED ISSUE #749: Flags `--cache-to` being split on comma
The way Nx parses arguments causes list to be split on comma when there is only a single value. This causes an issue when you use `cache-to` with `type=gha.mode=max`. There is currently no way to escape, however using `anyOf` in the schema can be used to ignore the splitting on comma when a single value is passed.
```bash
$ nx container project --cache-to typ=gha,mode=max
```

### PR DESCRIPTION
**Pull request by microwavekonijn**
Fixes #749 

Allows the passing of single flags of `cache-to` and `cache-from` without splitting them on the comma which would break commands like:
```bash
$ nx container <project> --cache-to type=gha,mode=max
```

### CODE REVIEW

**Comment by microwavekonijn** [comment]
@gperdomor any chance you can have a look at this?

File: packages/nx-container/src/executors/build/context.ts [hunk 1]
```diff
@@ -72,8 +72,8 @@ export async function getInputs(
     buildArgs: await getInputList('build-args', prefix, options['build-args'], true),
     buildContexts: await getInputList('build-contexts', prefix, options['build-contexts'], true),
     builder: core.getInput('builder', { prefix, fallback: options.builder }),
-    cacheFrom: await getInputList('cache-from', prefix, options['cache-from'], true),
-    cacheTo: await getInputList('cache-to', prefix, options['cache-to'], true),
+    cacheFrom: await getInputList('cache-from', prefix, [options['cache-from']].flat(), true),
+    cacheTo: await getInputList('cache-to', prefix, [options['cache-to']].flat(), true),
```
Comment (gperdomor) [inline packages/nx-container/src/executors/build/context.ts:76]: Can you validate the existence of options['cache-from'] and options['cache-to'], otherwise you can end with and `[undefined]` array

**Review by gperdomor — CHANGES_REQUESTED** [review]

File: packages/nx-container/src/executors/build/context.ts (hunk 1 above)
Comment (microwavekonijn) [reply packages/nx-container/src/executors/build/context.ts]: Should be fixed. I have added fallback empty array.

**Review by gperdomor — APPROVED** [review]
